package: nbsetuptools
user: anaconda-notebook

platform:
  - linux-64
  - osx-64
#  - win-64

engine:
  - python=2.7
  - python=3.4
  - python=3.5

install:
  - conda build --quiet conda.recipe -c anaconda-notebook
  - conda install nbsetuptools --use-local -c anaconda-notebook

test:
  - python -m unittest discover

build_targets: conda
