{% set data = load_setuptools()%}
package:
  name: nbsetuptools
  version: {{data.get('version')}}

requirements:
  build:
    - python

  run:
    - funcsigs
    - notebook
    - python

source:
  path: ../

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENSE
